remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Guia Prático para OSCs
description: Um guia completo para Organizações da Sociedade Civil

header_pages:
  - index.md
  - sobre.md
  - guia-pratico-oscs.md
  - preparacao-inicial.md
  - elaboracao-proposta.md
  - chamamento-publico.md
  - celebracao-parceria.md
  - execucao-projeto.md
  - monitoramento-avaliacao.md
  - prestacao-contas.md

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

baseurl: "/guia-pratico-oscs"
url: "https://phkawka.github.io"

include:
  - _includes

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

show_downloads: false

font_awesome_url: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css
